In [2]:
import numpy as np

In [3]:
my_lst = [1,2,3,4,5]

In [4]:
arr = np.array(my_lst)

In [5]:
type(arr)

numpy.ndarray

In [6]:
print(arr)

[1 2 3 4 5]


In [7]:
arr

array([1, 2, 3, 4, 5])

In [9]:
arr.shape

(5,)

In [10]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,0]
list3 = [11,12,13,14,15]

In [11]:
#converting these list into a 2-d array

In [14]:
arr = np.array([list1,list2,list3]) # this will convert these list into a 2-d array 

In [15]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9,  0],
       [11, 12, 13, 14, 15]])

In [20]:
arr.reshape(5,3) # this will reshape the array into 5 rows and 3 columns but make sure that the value you give to the  row and column must have multiplication equals to number of elements in array



array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 0, 11, 12],
       [13, 14, 15]])

Indexing

In [22]:
# a way to access all the elements of array
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9,  0],
       [11, 12, 13, 14, 15]])

In [24]:
# way to access a particular element by its index value
arr[2]

array([11, 12, 13, 14, 15])

In [25]:
arr[2,3]

np.int64(14)

In [26]:
arr[0,1
    ]

np.int64(2)

In [27]:
arr[0,0]

np.int64(1)

In [28]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9,  0],
       [11, 12, 13, 14, 15]])

In [30]:
# arr[row:,column] 
arr[0:2,:]  # it will give row 0th and 1st elements 

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0]])

In [32]:
arr[0:3,2:5]  # it will give values from row 0-2 and from column 2-4

array([[ 3,  4,  5],
       [ 8,  9,  0],
       [13, 14, 15]])

In [33]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9,  0],
       [11, 12, 13, 14, 15]])

In [36]:
arr[0:3,:3]

array([[ 1,  2,  3],
       [ 6,  7,  8],
       [11, 12, 13]])

In [37]:
#arrange fuctions arr =np.arrange(start,end) it will pick all the elements from start to one less than end

In [40]:
arr1 = np.arange(2,15)

In [42]:
arr1

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [43]:
arr1 = np.arange(1,20,step=3) # it will arrange all the elements in array from 1 to one less than 20 having gap of 3

In [44]:
arr1

array([ 1,  4,  7, 10, 13, 16, 19])

In [46]:
 np.linspace(1,8)  # it will give equally spaced elements with decimal value from 1-8

array([1.        , 1.14285714, 1.28571429, 1.42857143, 1.57142857,
       1.71428571, 1.85714286, 2.        , 2.14285714, 2.28571429,
       2.42857143, 2.57142857, 2.71428571, 2.85714286, 3.        ,
       3.14285714, 3.28571429, 3.42857143, 3.57142857, 3.71428571,
       3.85714286, 4.        , 4.14285714, 4.28571429, 4.42857143,
       4.57142857, 4.71428571, 4.85714286, 5.        , 5.14285714,
       5.28571429, 5.42857143, 5.57142857, 5.71428571, 5.85714286,
       6.        , 6.14285714, 6.28571429, 6.42857143, 6.57142857,
       6.71428571, 6.85714286, 7.        , 7.14285714, 7.28571429,
       7.42857143, 7.57142857, 7.71428571, 7.85714286, 8.        ])

In [50]:
arr1 = np.arange(1,9,step=2)

In [51]:
#copy function and broadcasing
arr1[3:] = 27

In [52]:
arr1

array([ 1,  3,  5, 27])

In [54]:
arr1 = arr.copy() #it will copy all the elements of arr to arr1

In [55]:
print(arr1)

[[ 1  2  3  4  5]
 [ 6  7  8  9  0]
 [11 12 13 14 15]]


In [59]:
arr1[0:2,2:5] = 100
print(arr1)

[[100 100 100 100 100]
 [100 100 100 100 100]
 [100 100 100 100 100]]


In [60]:
arr3 = np.arange(1,8)

In [61]:
arr3

array([1, 2, 3, 4, 5, 6, 7])

In [63]:
### some condition for exploratory data analysis
val = 4
arr3[arr3<val]  #it will give all elements which are less than val

array([1, 2, 3])

In [66]:
np.ones(5)  #it will give an array of elements having 1 as value

array([1., 1., 1., 1., 1.])

In [67]:
np.ones(4, dtype=int) # it will change the default datatype from float to int

array([1, 1, 1, 1])

In [69]:
np.random.rand(2,2)  #this will create an nxn array of elements with random values 

array([[0.1132775 , 0.5191085 ],
       [0.78072475, 0.64557701]])